version: '3.7'

services:
  currency-exchange-service:
    image: krishan5/currency-exchange-service:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network: